game:
  worlds:
    world-1:
      name: World name 113
      sector:
        length:
          x: 1
          y: 1
        size:
          x: 200
          y: 200
#    world-2:
#      name: World name 2
#      sector:
#        length:
#          x: 1
#          y: 1
#        size:
#          x: 200
#          y: 200

engine:
  fps: 32 # free plan max: 16

modules:
  players:
    className: PlayerModule
    path: modules/players/player.module.ts

  characters:
    className: CharacterModule
    path: modules/character/character.module.ts


