game:
  worlds:
    world-1:
      name: World name
      sector:
        length:
          x: 1
          y: 1
        size:
          x: 200
          y: 200

engine:
  fps: 16
  spatial:
    mode: worker # worker = partition object by total count objects | sector = partition objects by location
    move:
      checkOffset: 5000
      limitation:
        by: time # time = can't move object to other sector/worker before | edge = max distance from neighbor sector
        value: 60000 # ms

    translationDimension:
      x: x
      y: z

modules:
  players:
    className: PlayerModule
    path: modules/players/player.module.ts

  characters:
    className: CharacterModule
    path: modules/character/character.module.ts


