game:
  worlds:
    world-1:
      name: World name
      sector:
        length:
          x: 1
          y: 1
        size:
          x: 200
          y: 200

engine:
  fps: 16

modules:
  players:
    className: PlayerModule
    path: modules/players/player.module.ts

  characters:
    className: CharacterModule
    path: modules/character/character.module.ts


